export const SERVICE_DETAILS_FAILURE = "SERVICE_DETAILS_FAILURE";
export const SERVICE_DETAILS_REQUEST = "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCCESS = "SERVICE_DETAILS_SUCCESS";

export const SERVICES_FAILURE = "SERVICES_FAILURE";
export const SERVICES_REQUEST = "SERVICES_REQUEST";
export const SERVICES_SUCCESS = "SERVICES_SUCCESS";
